name: Test gh tool

on:
  push:
    branches:
      - master

jobs:
  gh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout micronaut-core
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: micronaut-projects/micronaut-core
          ref: master
          path: micronaut-core      
      - name: Update BOM
        uses: micronaut-projects/github-actions/update-bom@master
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: master # Or 1.3.x etc. "master" is the default and therefore it could be omitted
          property: micronautMavenPluginVersion # Refers to the key in gradle.properties
          version: "1.2.3"
