name: Test gh tool

on:
  push:
    branches:
      - master

jobs:
  gh:
    runs-on: ubuntu-latest
    steps:
      - name: Update BOM
        uses: micronaut-projects/github-actions/update-bom@master
        with:
          branch: master # Or 1.3.x etc. "master" is the default and therefore it could be omitted
          property: micronautMavenPluginVersion # Refers to the key in gradle.properties
          version: "1.2.3"
          