name: Release
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set the current release version
      id: release_version
      run: echo ::set-output name=release_version::${GITHUB_REF:11}
    - name: Get next minor version
      id: semvers
      uses: "WyriHaximus/github-action-next-semvers@master"
      with:
        version: ${{ steps.release_version.outputs.release_version }}
    - name: Run pre-release
      uses: alvarosanchez/github-actions/pre-release@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}    