name: Release
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set the current release version
      id: release_version
      run: echo ::set-output name=release_version::${GITHUB_REF:11}
    - name: Get next minor version
      id: semvers
      uses: "WyriHaximus/github-action-next-semvers@master"
      with:
        version: ${{ steps.release_version.outputs.release_version }}
    # - name: Remove SNAPSHOT from the version
      # run: sed -i 's/^projectVersion\=\(.*\)-SNAPSHOT$/projectVersion\=\1/' gradle.properties
    - name: Close old milestone
      run: |
        curl -s -X POST -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -H 'Content-Type: application/json' https://api.github.com/repos/${{ github.repository }}/milestones/`curl -s https://api.github.com/repos/${{ github.repository }}/milestones | jq -c '.[] | select (.title == "${{ steps.release_version.outputs.release_version }}") | .id'` -d '{"state":"closed"}'
    - name: Create new milestone
      run: |
        curl -s -X POST https://api.github.com/repos/${{ github.repository }}/milestones -d '{"title": "${{ steps.semvers.outputs.patch }}"}'
    - name: Print current branch
      run: git rev-parse --abbrev-ref HEAD
    - name: Set new snapshot version
      run: sed -i 's/^projectVersion\=\(.*\)$/projectVersion\=${{ steps.semvers.outputs.patch }}/' gradle.properties
    - name: Print gradle.properties
      run: cat gradle.properties
    - name: Commit and push gradle.properties
      run: git checkout master && git add gradle.properties && git commit -m "Back to snapshot" && git push origin master