name: Release
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Process version of the tag
      id: version
      uses: ncipollo/semantic-version-action@v1
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps.version.outputs) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump previous tag
      env:
        PREVIOUS_TAG: ${{ steps.version.outputs.previous_tag }}
      run: echo "$PREVIOUS_TAG"
    - name: Set the current release version
      id: release_version
      run: echo ::set-output name=release_version::${GITHUB_REF:11}
    - name: Get next minor version
      id: semvers
      uses: "WyriHaximus/github-action-next-semvers@master"
      with:
        version: ${{ steps.release_version.outputs.release_version }}
    - name: Run post release script
      run: ./.github/post_release.sh "${{ secrets.GITHUB_TOKEN }}" "${{ github.repository }}" "${{ steps.release_version.outputs.release_version }}" "${{ steps.semvers.outputs.patch }}"