name: Release
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run pre-release
      uses: micronaut-projects/github-actions/pre-release@master
    - run: echo "Doing actual release"
    - name: Run post-release
      uses: micronaut-projects/github-actions/post-release@master
