# This is a basic workflow to help you get started with Actions

name: REST API test

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: octokit/request-action@v2.x
        id: get_default_branch
        with:
          route: GET /repos/{owner}/{repo}
          owner: micronaut-projects
          repo: micronaut-starter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo default branch: ${{ fromJson(steps.get_default_branch.outputs.data).default_branch }}"
